/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NotreEcoleRouteImport } from './routes/notre-ecole'
import { Route as VieScolaireRouteImport } from './routes/vie-scolaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreEcoleRoute = NotreEcoleRouteImport.update({
  id: '/notre-ecole',
  path: '/notre-ecole',
  getParentRoute: () => rootRouteImport,
} as any)
const VieScolaireRoute = VieScolaireRouteImport.update({
  id: '/vie-scolaire',
  path: '/vie-scolaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admissions' | '/contact' | '/notre-ecole' | '/vie-scolaire'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admissions' | '/contact' | '/notre-ecole' | '/vie-scolaire'
  id:
    | '__root__'
    | '/'
    | '/admissions'
    | '/contact'
    | '/notre-ecole'
    | '/vie-scolaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  NotreEcoleRoute: typeof NotreEcoleRoute
  VieScolaireRoute: typeof VieScolaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-ecole': {
      id: '/notre-ecole'
      path: '/notre-ecole'
      fullPath: '/notre-ecole'
      preLoaderRoute: typeof NotreEcoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vie-scolaire': {
      id: '/vie-scolaire'
      path: '/vie-scolaire'
      fullPath: '/vie-scolaire'
      preLoaderRoute: typeof VieScolaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  NotreEcoleRoute: NotreEcoleRoute,
  VieScolaireRoute: VieScolaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
